import { useMemo, useState } from "react";
import { ArrowUpRight, Clipboard, Megaphone, Share2, Zap } from "lucide-react";
import { buildViralContent } from "../lib/viral";
import type { ShareLink } from "../lib/viral";
import type { TournamentData } from "../types";

type Props = {
  data: TournamentData;
  routeWhatChangedMatchId?: string;
};

function signedPercent(value: number) {
  return `${value > 0 ? "+" : ""}${value}%`;
}

function ShareButton({ link, onCopy }: { link: ShareLink; onCopy: (url: string) => void }) {
  if (link.label === "Copy") {
    return (
      <button onClick={() => onCopy(link.url)}>
        <Clipboard size={14} />
        Copy
      </button>
    );
  }

  return (
    <a href={link.url} target="_blank" rel="noreferrer">
      <Share2 size={14} />
      {link.label}
    </a>
  );
}

export function PredictionsPage({ data, routeWhatChangedMatchId }: Props) {
  const [copied, setCopied] = useState("");
  const origin = typeof window === "undefined" ? "" : window.location.origin;
  const content = useMemo(() => buildViralContent(data, origin), [data, origin]);
  const prediction = content.prediction;
  const featuredChange =
    (routeWhatChangedMatchId
      ? content.whatChanged.find((item) => item.matchId === routeWhatChangedMatchId)
      : undefined) ?? content.whatChanged[0];

  async function copyUrl(url: string) {
    try {
      await navigator.clipboard.writeText(url);
      setCopied(url);
      window.setTimeout(() => setCopied(""), 1600);
    } catch {
      setCopied("");
    }
  }

  return (
    <div className="viral-stack">
      <section className="lab-intro viral-intro">
        <div>
          <span className="eyebrow">Model output</span>
          <h2>Win probabilities and momentum shifts</h2>
          <p>
            Poisson-derived match predictions, probability swings from finished results, and shareable match cards — updated every 45 seconds.
          </p>
        </div>
        <div className="model-badge"><Zap size={16} /> {content.whatChanged.length} swings tracked</div>
      </section>

      {prediction && (
        <section className="viral-hero-grid">
          <article className="panel prediction-card">
            <div className="section-heading">
              <div>
                <span className="eyebrow">{prediction.subtitle}</span>
                <h3>{prediction.title}</h3>
              </div>
              <Zap size={19} />
            </div>

            <div className="share-card-preview">
              <span>Generated by Touchline26.com</span>
              <h4>{prediction.title}</h4>
              <div className="prediction-bars">
                <div>
                  <strong>{prediction.homeName}</strong>
                  <span><i style={{ width: `${prediction.homePercent}%` }} /></span>
                  <b>{prediction.homePercent}%</b>
                </div>
                <div>
                  <strong>Draw</strong>
                  <span><i style={{ width: `${prediction.drawPercent}%` }} /></span>
                  <b>{prediction.drawPercent}%</b>
                </div>
                <div>
                  <strong>{prediction.awayName}</strong>
                  <span><i style={{ width: `${prediction.awayPercent}%` }} /></span>
                  <b>{prediction.awayPercent}%</b>
                </div>
              </div>
            </div>

            <div className="viral-actions">
              {prediction.shareLinks.map((link) => (
                <ShareButton link={link} onCopy={copyUrl} key={link.label} />
              ))}
              <a href={prediction.cardUrl} target="_blank" rel="noreferrer">
                <ArrowUpRight size={14} />
                Card
              </a>
            </div>
            {copied === prediction.pageUrl && <p className="copy-status">Link copied.</p>}
          </article>

          <article className="panel change-card">
            <div className="section-heading">
              <div>
                <span className="eyebrow">{routeWhatChangedMatchId ? "What changed after this match" : "Highest ROI feature"}</span>
                <h3>What Changed?</h3>
              </div>
              <Megaphone size={19} />
            </div>
            {featuredChange ? (
              <>
                <div className="change-score">
                  <span>{featuredChange.teamName}</span>
                  <strong>{signedPercent(featuredChange.change)}</strong>
                  <p>{featuredChange.before}% before match · {featuredChange.after}% after match</p>
                </div>
                <div className="change-meter">
                  <i style={{ left: `${featuredChange.before}%` }} />
                  <b style={{ width: `${featuredChange.after}%` }} />
                </div>
                <p className="model-note">{featuredChange.result}</p>
                <div className="viral-actions">
                  <a
                    href={`https://twitter.com/intent/tweet?text=${encodeURIComponent(`${featuredChange.teamName} advancement: ${featuredChange.before}% → ${featuredChange.after}% after ${featuredChange.result}. Generated by Touchline26.com`)}`}
                    target="_blank"
                    rel="noreferrer"
                  >
                    <Share2 size={14} />
                    X
                  </a>
                  <a
                    href={`https://wa.me/?text=${encodeURIComponent(`${featuredChange.teamName} ${signedPercent(featuredChange.change)} — ${featuredChange.before}% before, ${featuredChange.after}% after. ${origin}/what-changed/${encodeURIComponent(featuredChange.matchId)}`)}`}
                    target="_blank"
                    rel="noreferrer"
                  >
                    <Share2 size={14} />
                    WhatsApp
                  </a>
                  <a href={featuredChange.cardUrl} target="_blank" rel="noreferrer">
                    <ArrowUpRight size={14} />
                    Card
                  </a>
                </div>
              </>
            ) : (
              <p className="empty-copy">What Changed cards will appear as finished matches arrive.</p>
            )}
          </article>
        </section>
      )}

      <section className="viral-grid">
        <article className="panel viral-list">
          <div className="section-heading">
            <div>
              <span className="eyebrow">After match</span>
              <h3>Biggest swings</h3>
            </div>
          </div>
          {content.whatChanged.length ? content.whatChanged.slice(0, 5).map((item) => (
            <div className="viral-row" key={`${item.matchId}-${item.teamName}`}>
              <div>
                <strong>{item.teamName}</strong>
                <span>{item.result}</span>
              </div>
              <b className={item.change >= 0 ? "positive" : "negative"}>{signedPercent(item.change)}</b>
            </div>
          )) : <p className="empty-copy">Probability swings will appear as matches finish.</p>}
        </article>
      </section>
    </div>
  );
}
