import { useMemo, useState } from "react";
import {
  ArrowUpRight,
  Clipboard,
  Flame,
  Newspaper,
  Megaphone,
  Share2,
  Sparkles,
  Trophy,
  Zap,
} from "lucide-react";
import { buildViralContent } from "../lib/viral";
import type { ShareLink } from "../lib/viral";
import type { TournamentData } from "../types";

type Props = {
  data: TournamentData;
};

function signedPercent(value: number) {
  return `${value > 0 ? "+" : ""}${value}%`;
}

function ShareButton({ link, onCopy }: { link: ShareLink; onCopy: (url: string) => void }) {
  if (link.label === "Copy") {
    return (
      <button onClick={() => onCopy(link.url)}>
        <Clipboard size={14} />
        Copy
      </button>
    );
  }

  return (
    <a href={link.url} target="_blank" rel="noreferrer">
      <Share2 size={14} />
      {link.label}
    </a>
  );
}

export function ViralEngine({ data }: Props) {
  const [copied, setCopied] = useState("");
  const origin = typeof window === "undefined" ? "" : window.location.origin;
  const content = useMemo(() => buildViralContent(data, origin), [data, origin]);
  const prediction = content.prediction;
  const topChange = content.whatChanged[0];

  async function copyUrl(url: string) {
    try {
      await navigator.clipboard.writeText(url);
      setCopied(url);
      window.setTimeout(() => setCopied(""), 1600);
    } catch {
      setCopied("");
    }
  }

  return (
    <div className="viral-stack">
      <section className="lab-intro viral-intro">
        <div>
          <span className="eyebrow">Growth engine</span>
          <h2>Shareable World Cup moments</h2>
          <p>
            Predictions, probability swings, upsets, rankings, and post templates generated from the same live model as the command center.
          </p>
        </div>
        <div className="model-badge"><Sparkles size={16} /> {content.socialPosts.length} posts ready</div>
      </section>

      {prediction && (
        <section className="viral-hero-grid">
          <article className="panel prediction-card">
            <div className="section-heading">
              <div>
                <span className="eyebrow">{prediction.subtitle}</span>
                <h3>{prediction.title}</h3>
              </div>
              <Zap size={19} />
            </div>

            <div className="share-card-preview">
              <span>Generated by Touchline26.com</span>
              <h4>{prediction.title}</h4>
              <div className="prediction-bars">
                <div>
                  <strong>{prediction.homeName}</strong>
                  <span><i style={{ width: `${prediction.homePercent}%` }} /></span>
                  <b>{prediction.homePercent}%</b>
                </div>
                <div>
                  <strong>Draw</strong>
                  <span><i style={{ width: `${prediction.drawPercent}%` }} /></span>
                  <b>{prediction.drawPercent}%</b>
                </div>
                <div>
                  <strong>{prediction.awayName}</strong>
                  <span><i style={{ width: `${prediction.awayPercent}%` }} /></span>
                  <b>{prediction.awayPercent}%</b>
                </div>
              </div>
            </div>

            <div className="viral-actions">
              {prediction.shareLinks.map((link) => (
                <ShareButton link={link} onCopy={copyUrl} key={link.label} />
              ))}
              <a href={prediction.cardUrl} target="_blank" rel="noreferrer">
                <ArrowUpRight size={14} />
                Card
              </a>
            </div>
            {copied === prediction.pageUrl && <p className="copy-status">Link copied.</p>}
          </article>

          <article className="panel change-card">
            <div className="section-heading">
              <div>
                <span className="eyebrow">Highest ROI feature</span>
                <h3>What Changed?</h3>
              </div>
              <Megaphone size={19} />
            </div>
            {topChange ? (
              <>
                <div className="change-score">
                  <span>{topChange.teamName}</span>
                  <strong>{signedPercent(topChange.change)}</strong>
                  <p>{topChange.before}% before match · {topChange.after}% after match</p>
                </div>
                <div className="change-meter">
                  <i style={{ left: `${topChange.before}%` }} />
                  <b style={{ width: `${topChange.after}%` }} />
                </div>
                <p className="model-note">{topChange.result}</p>
              </>
            ) : (
              <p className="empty-copy">What Changed cards will appear as finished matches arrive.</p>
            )}
          </article>
        </section>
      )}

      <section className="viral-grid">
        <article className="panel viral-list story-list">
          <div className="section-heading">
            <div>
              <span className="eyebrow">Content engine</span>
              <h3>Generated stories</h3>
            </div>
            <Newspaper size={19} />
          </div>
          {content.contentStories.slice(0, 6).map((story) => (
            <div className="story-row" key={story.slug}>
              <span>{story.phase}</span>
              <a href={story.pageUrl}>{story.title}</a>
              <p>{story.summary}</p>
              <div>
                <button onClick={() => copyUrl(story.summary)}>Copy summary</button>
                <a href={story.cardUrl} target="_blank" rel="noreferrer">Card</a>
              </div>
            </div>
          ))}
        </article>

        <article className="panel viral-list">
          <div className="section-heading">
            <div>
              <span className="eyebrow">After match</span>
              <h3>Biggest swings</h3>
            </div>
          </div>
          {content.whatChanged.slice(0, 5).map((item) => (
            <div className="viral-row" key={`${item.matchId}-${item.teamName}`}>
              <div>
                <strong>{item.teamName}</strong>
                <span>{item.result}</span>
              </div>
              <b className={item.change >= 0 ? "positive" : "negative"}>{signedPercent(item.change)}</b>
            </div>
          ))}
        </article>

        <article className="panel viral-list">
          <div className="section-heading">
            <div>
              <span className="eyebrow">Arguments</span>
              <h3>Upset meter</h3>
            </div>
            <Flame size={19} />
          </div>
          {content.upsets.length ? content.upsets.slice(0, 5).map((item, index) => (
            <div className="viral-row" key={item.matchId}>
              <div>
                <strong>{index + 1}. {item.title}</strong>
                <span>{item.score} · upset score {item.upsetScore}</span>
              </div>
              <b>{item.winnerRating}</b>
            </div>
          )) : <p className="empty-copy">No model-rated upsets yet.</p>}
        </article>

        <article className="panel viral-list power-list">
          <div className="section-heading">
            <div>
              <span className="eyebrow">Daily</span>
              <h3>Power rankings</h3>
            </div>
            <Trophy size={19} />
          </div>
          {content.powerRankings.slice(0, 8).map((team) => (
            <div className="viral-row" key={team.teamId}>
              <div>
                <strong>{team.rank}. {team.teamName}</strong>
                <span>{team.note} · {team.movementLabel}</span>
              </div>
              <b>{team.score}</b>
            </div>
          ))}
        </article>

        <article className="panel viral-list post-list">
          <div className="section-heading">
            <div>
              <span className="eyebrow">Automation queue</span>
              <h3>Post templates</h3>
            </div>
          </div>
          {content.socialPosts.map((post) => (
            <div className="post-template" key={`${post.phase}-${post.title}`}>
              <span>{post.phase}</span>
              <strong>{post.title}</strong>
              <p>{post.body}</p>
              <div>
                <button onClick={() => copyUrl(post.body)}>Copy text</button>
                <a href={post.cardUrl} target="_blank" rel="noreferrer">Card</a>
              </div>
            </div>
          ))}
        </article>
      </section>

      <section className="panel seo-panel">
        <div className="section-heading">
          <div>
            <span className="eyebrow">SEO and AI visibility</span>
            <h3>Generated page inventory</h3>
          </div>
          <span>{content.seoPages.length} targets</span>
        </div>
        <div className="seo-grid">
          {content.seoPages.slice(0, 12).map((page) => (
            <a href={page.path} key={page.path}>
              <strong>{page.title}</strong>
              <span>{page.description}</span>
            </a>
          ))}
        </div>
      </section>
    </div>
  );
}
